stages:
  - package

variables:
  LC_ALL: "fr_FR.UTF-8"
  LANG: "fr_FR.UTF-8"


#build_android:
#  stage: package
#  image:
#    name: xetics/flutter:1.9.1-stable
#  tags:
#    - flutter-android
#  script: flutter build apk --release --build-number=$CI_PIPELINE_ID
#  artifacts:
#    paths:
#      - build/app/outputs/apk/release/app-release.apk
#    expire_in: 1 day

build_ios:
  stage: package
  image:
    name: xetics/flutter:1.9.1-stable
  tags:
    - flutter-ios
  script:
    - flutter build ios --release --build-number=$CI_PIPELINE_ID
  artifacts:
    untracked: true
    expire_in: 1 day
  only:
    - master